name: shopverse

on :
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AWS_REGION: ap-southeast-1
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
jobs:
   tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
     - name: checkout 
       uses: actions/checkout@v4

     - name: set up go
       uses: actions/setup-go@v5
       with:
         go-version: 1.24

     - name: update go.sum
       working-directory: ./backend
       run: go mod tidy

     - name: run tests
       working-directory: ./backend
       run: go test ./... 

     - name: set up node js
       uses: actions/setup-node@v4
       with:
         node-version: "18"

     - name: install frontend dependencies
       working-directory: ./frontend
       run: npm install

     - name: Run frontend lint
       working-directory: ./frontend
       run: npx eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0 --config .eslintrc.cjs
     
   security-scan:
    name: security scan using trivy
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: build forntend image
        run: docker build -t shopverse-frontend:scan ./frontend

      - name: build backend image
        run: docker build -t shopverse-backend:scan ./backend

      - name: install trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy scan on frontend
        run: |
          trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed --format table shopverse-frontend:scan

      - name: Run Trivy scan on backend
        run: |
          trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed --format table shopverse-backend:scan
  
   build-and-push:
    name: Build, Tag & Push
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repositories exist
        run: |
          for repo in shopverse-frontend shopverse-backend ; do
            aws ecr describe-repositories --repository-names $repo --region ${{ env.AWS_REGION }} 2>/dev/null || \
            aws ecr create-repository --repository-name $repo --region ${{ env.AWS_REGION }}
          done

      - name: Build and tag frontend image
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/shopverse-frontend:${{ github.sha }} \
                        -t ${{ env.ECR_REGISTRY }}/shopverse-frontend:latest \
                        ./frontend

      - name: Build and tag backend image
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/shopverse-backend:${{ github.sha }} \
                        -t ${{ env.ECR_REGISTRY }}/shopverse-backend:latest \
                        ./backend

      - name: Push frontend image
        run: |
          docker push ${{ env.ECR_REGISTRY }}/shopverse-frontend:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/shopverse-frontend:latest

      - name: Push backend image
        run: |
          docker push ${{ env.ECR_REGISTRY }}/shopverse-backend:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY }}/shopverse-backend:latest
